apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: mirroring
spec:
  hosts:
    - reviews
  http:
  - route:
    - destination:
        host: reviews
        subset: v1
      weight: 100
    mirror:
      host: reviews
      subset: v2
