apiVersion: networking.istio.io/v1alpha3
kind: DestinationRule
metadata:
  name: bookinfo
spec:
  host: reviews
  trafficPolicy:
    outlierDetection:
      consecutive5xxErrors: 10
      interval: 1s
      baseEjectionTime: 3m
      maxEjectionPercent: 100
