apiVersion: linkerd.io/v1alpha2
kind: ServiceProfile
metadata:
  name: ratings.default.svc.cluster.local
  namespace: default
spec:
  routes:
    - condition:
        method: GET
        pathRegex: /ratings/[^/]*
      name: GET /ratings/{id}
      isRetryable: true
  retryBudget:
    retryRatio: 0.2
    minRetriesPerSecond: 10
    ttl: 20s
