apiVersion: linkerd.io/v1alpha2
kind: ServiceProfile
metadata:
  name: bb-v1.default.svc.cluster.local
  namespace: default
spec:
  routes:
    - condition:
        method: GET
        pathRegex: /
      name: GET /
      timeout: 300ms
